#[derive(Debug)]
pub enum CountryCode {
    AFG,
    ALA,
    ALB,
    DZA,
    ASM,
    AND,
    AGO,
    AIA,
    ATA,
    ATG,
    ARG,
    ARM,
    ABW,
    AUS,
    AUT,
    AZE,
    BHS,
    BHR,
    BGD,
    BRB,
    BLR,
    BEL,
    BLZ,
    BEN,
    BMU,
    BTN,
    BOL,
    BES,
    BIH,
    BWA,
    BVT,
    BRA,
    IOT,
    BRN,
    BGR,
    BFA,
    BDI,
    CPV,
    KHM,
    CMR,
    CAN,
    CYM,
    CAF,
    TCD,
    CHL,
    CHN,
    CXR,
    CCK,
    COL,
    COM,
    COG,
    COD,
    COK,
    CRI,
    CIV,
    HRV,
    CUB,
    CUW,
    CYP,
    CZE,
    DNK,
    DJI,
    DMA,
    DOM,
    ECU,
    EGY,
    SLV,
    GNQ,
    ERI,
    EST,
    SWZ,
    ETH,
    FLK,
    FRO,
    FJI,
    FIN,
    FRA,
    GUF,
    PYF,
    ATF,
    GAB,
    GMB,
    GEO,
    DEU,
    GHA,
    GIB,
    GRC,
    GRL,
    GRD,
    GLP,
    GUM,
    GTM,
    GGY,
    GIN,
    GNB,
    GUY,
    HTI,
    HMD,
    VAT,
    HND,
    HKG,
    HUN,
    ISL,
    IND,
    IDN,
    IRN,
    IRQ,
    IRL,
    IMN,
    ISR,
    ITA,
    JAM,
    JPN,
    JEY,
    JOR,
    KAZ,
    KEN,
    KIR,
    PRK,
    KOR,
    KWT,
    KGZ,
    LAO,
    LVA,
    LBN,
    LSO,
    LBR,
    LBY,
    LIE,
    LTU,
    LUX,
    MAC,
    MDG,
    MWI,
    MYS,
    MDV,
    MLI,
    MLT,
    MHL,
    MTQ,
    MRT,
    MUS,
    MYT,
    MEX,
    FSM,
    MDA,
    MCO,
    MNG,
    MNE,
    MSR,
    MAR,
    MOZ,
    MMR,
    NAM,
    NRU,
    NPL,
    NLD,
    NCL,
    NZL,
    NIC,
    NER,
    NGA,
    NIU,
    NFK,
    MKD,
    MNP,
    NOR,
    OMN,
    PAK,
    PLW,
    PSE,
    PAN,
    PNG,
    PRY,
    PER,
    PHL,
    PCN,
    POL,
    PRT,
    PRI,
    QAT,
    REU,
    ROU,
    RUS,
    RWA,
    BLM,
    SHN,
    KNA,
    LCA,
    MAF,
    SPM,
    VCT,
    WSM,
    SMR,
    STP,
    SAU,
    SEN,
    SRB,
    SYC,
    SLE,
    SGP,
    SXM,
    SVK,
    SVN,
    SLB,
    SOM,
    ZAF,
    SGS,
    SSD,
    ESP,
    LKA,
    SDN,
    SUR,
    SJM,
    SWE,
    CHE,
    SYR,
    TWN,
    TJK,
    TZA,
    THA,
    TLS,
    TGO,
    TKL,
    TON,
    TTO,
    TUN,
    TUR,
    TKM,
    TCA,
    TUV,
    UGA,
    UKR,
    ARE,
    GBR,
    USA,
    UMI,
    URY,
    UZB,
    VUT,
    VEN,
    VNM,
    VGB,
    VIR,
    WLF,
    ESH,
    YEM,
    ZMB,
    ZWE,
}

impl CountryCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            CountryCode::AFG => "Afghanistan",
            CountryCode::ALA => "Aland Islands",
            CountryCode::ALB => "Albania",
            CountryCode::DZA => "Algeria",
            CountryCode::ASM => "American Samoa",
            CountryCode::AND => "Andorra",
            CountryCode::AGO => "Angola",
            CountryCode::AIA => "Anguilla",
            CountryCode::ATA => "Antarctica",
            CountryCode::ATG => "Antigua and Barbuda",
            CountryCode::ARG => "Argentina",
            CountryCode::ARM => "Armenia",
            CountryCode::ABW => "Aruba",
            CountryCode::AUS => "Australia",
            CountryCode::AUT => "Austria",
            CountryCode::AZE => "Azerbaijan",
            CountryCode::BHS => "Bahamas",
            CountryCode::BHR => "Bahrain",
            CountryCode::BGD => "Bangladesh",
            CountryCode::BRB => "Barbados",
            CountryCode::BLR => "Belarus",
            CountryCode::BEL => "Belgium",
            CountryCode::BLZ => "Belize",
            CountryCode::BEN => "Benin",
            CountryCode::BMU => "Bermuda",
            CountryCode::BTN => "Bhutan",
            CountryCode::BOL => "Bolivia (Plurinational State of)",
            CountryCode::BES => "Bonaire, Sint Eustatius and Saba",
            CountryCode::BIH => "Bosnia and Herzegovina",
            CountryCode::BWA => "Botswana",
            CountryCode::BVT => "Bouvet Island",
            CountryCode::BRA => "Brazil",
            CountryCode::IOT => "British Indian Ocean Territory",
            CountryCode::BRN => "Brunei Darussalam",
            CountryCode::BGR => "Bulgaria",
            CountryCode::BFA => "Burkina Faso",
            CountryCode::BDI => "Burundi",
            CountryCode::CPV => "Cabo Verde",
            CountryCode::KHM => "Cambodia",
            CountryCode::CMR => "Cameroon",
            CountryCode::CAN => "Canada",
            CountryCode::CYM => "Cayman Islands",
            CountryCode::CAF => "Central African Republic",
            CountryCode::TCD => "Chad",
            CountryCode::CHL => "Chile",
            CountryCode::CHN => "China",
            CountryCode::CXR => "Christmas Island",
            CountryCode::CCK => "Cocos (Keeling) Islands",
            CountryCode::COL => "Colombia",
            CountryCode::COM => "Comoros",
            CountryCode::COG => "Congo",
            CountryCode::COD => "Congo, Democratic Republic of the",
            CountryCode::COK => "Cook Islands",
            CountryCode::CRI => "Costa Rica",
            CountryCode::CIV => "Cote d'Ivoire",
            CountryCode::HRV => "Croatia",
            CountryCode::CUB => "Cuba",
            CountryCode::CUW => "Curacao",
            CountryCode::CYP => "Cyprus",
            CountryCode::CZE => "Czechia",
            CountryCode::DNK => "Denmark",
            CountryCode::DJI => "Djibouti",
            CountryCode::DMA => "Dominica",
            CountryCode::DOM => "Dominican Republic",
            CountryCode::ECU => "Ecuador",
            CountryCode::EGY => "Egypt",
            CountryCode::SLV => "El Salvador",
            CountryCode::GNQ => "Equatorial Guinea",
            CountryCode::ERI => "Eritrea",
            CountryCode::EST => "Estonia",
            CountryCode::SWZ => "Eswatini",
            CountryCode::ETH => "Ethiopia",
            CountryCode::FLK => "Falkland Islands (Malvinas)",
            CountryCode::FRO => "Faroe Islands",
            CountryCode::FJI => "Fiji",
            CountryCode::FIN => "Finland",
            CountryCode::FRA => "France",
            CountryCode::GUF => "French Guiana",
            CountryCode::PYF => "French Polynesia",
            CountryCode::ATF => "French Southern Territories",
            CountryCode::GAB => "Gabon",
            CountryCode::GMB => "Gambia",
            CountryCode::GEO => "Georgia",
            CountryCode::DEU => "Germany",
            CountryCode::GHA => "Ghana",
            CountryCode::GIB => "Gibraltar",
            CountryCode::GRC => "Greece",
            CountryCode::GRL => "Greenland",
            CountryCode::GRD => "Grenada",
            CountryCode::GLP => "Guadeloupe",
            CountryCode::GUM => "Guam",
            CountryCode::GTM => "Guatemala",
            CountryCode::GGY => "Guernsey",
            CountryCode::GIN => "Guinea",
            CountryCode::GNB => "Guinea-Bissau",
            CountryCode::GUY => "Guyana",
            CountryCode::HTI => "Haiti",
            CountryCode::HMD => "Heard Island and McDonald Islands",
            CountryCode::VAT => "Holy See",
            CountryCode::HND => "Honduras",
            CountryCode::HKG => "Hong Kong",
            CountryCode::HUN => "Hungary",
            CountryCode::ISL => "Iceland",
            CountryCode::IND => "India",
            CountryCode::IDN => "Indonesia",
            CountryCode::IRN => "Iran (Islamic Republic of)",
            CountryCode::IRQ => "Iraq",
            CountryCode::IRL => "Ireland",
            CountryCode::IMN => "Isle of Man",
            CountryCode::ISR => "Israel",
            CountryCode::ITA => "Italy",
            CountryCode::JAM => "Jamaica",
            CountryCode::JPN => "Japan",
            CountryCode::JEY => "Jersey",
            CountryCode::JOR => "Jordan",
            CountryCode::KAZ => "Kazakhstan",
            CountryCode::KEN => "Kenya",
            CountryCode::KIR => "Kiribati",
            CountryCode::PRK => "Korea (Democratic People's Republic of)",
            CountryCode::KOR => "Korea, Republic of",
            CountryCode::KWT => "Kuwait",
            CountryCode::KGZ => "Kyrgyzstan",
            CountryCode::LAO => "Lao People's Democratic Republic",
            CountryCode::LVA => "Latvia",
            CountryCode::LBN => "Lebanon",
            CountryCode::LSO => "Lesotho",
            CountryCode::LBR => "Liberia",
            CountryCode::LBY => "Libya",
            CountryCode::LIE => "Liechtenstein",
            CountryCode::LTU => "Lithuania",
            CountryCode::LUX => "Luxembourg",
            CountryCode::MAC => "Macao",
            CountryCode::MDG => "Madagascar",
            CountryCode::MWI => "Malawi",
            CountryCode::MYS => "Malaysia",
            CountryCode::MDV => "Maldives",
            CountryCode::MLI => "Mali",
            CountryCode::MLT => "Malta",
            CountryCode::MHL => "Marshall Islands",
            CountryCode::MTQ => "Martinique",
            CountryCode::MRT => "Mauritania",
            CountryCode::MUS => "Mauritius",
            CountryCode::MYT => "Mayotte",
            CountryCode::MEX => "Mexico",
            CountryCode::FSM => "Micronesia (Federated States of)",
            CountryCode::MDA => "Moldova, Republic of",
            CountryCode::MCO => "Monaco",
            CountryCode::MNG => "Mongolia",
            CountryCode::MNE => "Montenegro",
            CountryCode::MSR => "Montserrat",
            CountryCode::MAR => "Morocco",
            CountryCode::MOZ => "Mozambique",
            CountryCode::MMR => "Myanmar",
            CountryCode::NAM => "Namibia",
            CountryCode::NRU => "Nauru",
            CountryCode::NPL => "Nepal",
            CountryCode::NLD => "Netherlands",
            CountryCode::NCL => "New Caledonia",
            CountryCode::NZL => "New Zealand",
            CountryCode::NIC => "Nicaragua",
            CountryCode::NER => "Niger",
            CountryCode::NGA => "Nigeria",
            CountryCode::NIU => "Niue",
            CountryCode::NFK => "Norfolk Island",
            CountryCode::MKD => "North Macedonia",
            CountryCode::MNP => "Northern Mariana Islands",
            CountryCode::NOR => "Norway",
            CountryCode::OMN => "Oman",
            CountryCode::PAK => "Pakistan",
            CountryCode::PLW => "Palau",
            CountryCode::PSE => "Palestine, State of",
            CountryCode::PAN => "Panama",
            CountryCode::PNG => "Papua New Guinea",
            CountryCode::PRY => "Paraguay",
            CountryCode::PER => "Peru",
            CountryCode::PHL => "Philippines",
            CountryCode::PCN => "Pitcairn",
            CountryCode::POL => "Poland",
            CountryCode::PRT => "Portugal",
            CountryCode::PRI => "Puerto Rico",
            CountryCode::QAT => "Qatar",
            CountryCode::REU => "Reunion",
            CountryCode::ROU => "Romania",
            CountryCode::RUS => "Russian Federation",
            CountryCode::RWA => "Rwanda",
            CountryCode::BLM => "Saint Barthelemy",
            CountryCode::SHN => "Saint Helena, Ascension and Tristan da Cunha",
            CountryCode::KNA => "Saint Kitts and Nevis",
            CountryCode::LCA => "Saint Lucia",
            CountryCode::MAF => "Saint Martin (French part)",
            CountryCode::SPM => "Saint Pierre and Miquelon",
            CountryCode::VCT => "Saint Vincent and the Grenadines",
            CountryCode::WSM => "Samoa",
            CountryCode::SMR => "San Marino",
            CountryCode::STP => "Sao Tome and Principe",
            CountryCode::SAU => "Saudi Arabia",
            CountryCode::SEN => "Senegal",
            CountryCode::SRB => "Serbia",
            CountryCode::SYC => "Seychelles",
            CountryCode::SLE => "Sierra Leone",
            CountryCode::SGP => "Singapore",
            CountryCode::SXM => "Sint Maarten (Dutch part)",
            CountryCode::SVK => "Slovakia",
            CountryCode::SVN => "Slovenia",
            CountryCode::SLB => "Solomon Islands",
            CountryCode::SOM => "Somalia",
            CountryCode::ZAF => "South Africa",
            CountryCode::SGS => "South Georgia and the South Sandwich Islands",
            CountryCode::SSD => "South Sudan",
            CountryCode::ESP => "Spain",
            CountryCode::LKA => "Sri Lanka",
            CountryCode::SDN => "Sudan",
            CountryCode::SUR => "Suriname",
            CountryCode::SJM => "Svalbard and Jan Mayen",
            CountryCode::SWE => "Sweden",
            CountryCode::CHE => "Switzerland",
            CountryCode::SYR => "Syrian Arab Republic",
            CountryCode::TWN => "Taiwan, Province of China",
            CountryCode::TJK => "Tajikistan",
            CountryCode::TZA => "Tanzania, United Republic of",
            CountryCode::THA => "Thailand",
            CountryCode::TLS => "Timor-Leste",
            CountryCode::TGO => "Togo",
            CountryCode::TKL => "Tokelau",
            CountryCode::TON => "Tonga",
            CountryCode::TTO => "Trinidad and Tobago",
            CountryCode::TUN => "Tunisia",
            CountryCode::TUR => "Turkey",
            CountryCode::TKM => "Turkmenistan",
            CountryCode::TCA => "Turks and Caicos Islands",
            CountryCode::TUV => "Tuvalu",
            CountryCode::UGA => "Uganda",
            CountryCode::UKR => "Ukraine",
            CountryCode::ARE => "United Arab Emirates",
            CountryCode::GBR => "United Kingdom of Great Britain and Northern Ireland",
            CountryCode::USA => "United States of America",
            CountryCode::UMI => "United States Minor Outlying Islands",
            CountryCode::URY => "Uruguay",
            CountryCode::UZB => "Uzbekistan",
            CountryCode::VUT => "Vanuatu",
            CountryCode::VEN => "Venezuela (Bolivarian Republic of)",
            CountryCode::VNM => "Viet Nam",
            CountryCode::VGB => "Virgin Islands (British)",
            CountryCode::VIR => "Virgin Islands (U.S.)",
            CountryCode::WLF => "Wallis and Futuna",
            CountryCode::ESH => "Western Sahara",
            CountryCode::YEM => "Yemen",
            CountryCode::ZMB => "Zambia",
            CountryCode::ZWE => "Zimbabwe",
        }
    }
}
